


// test POST api
POST http://localhost:5000/api/loginBusiness
Content-Type: application/json

{
    "firstName" : "Otto",
    "lastName": "Kafka"
}
###



// Business registration 1
POST http://localhost:5000/api/registerBusiness
Content-Type: application/json

{
    "firstName" : "John",
    "lastName": "Mick",
    "email": "test1@email.com",
    "password": "123456",
    "phoneNumber": "123456789"
}
###


// Business login 
POST http://localhost:5000/api/loginBusiness
Content-Type: application/json

{
     "email": "test1@email.com",
     "password": "123456"
}
###



// test GET api
GET http://localhost:5000/api/availability/test
Content-Type: application/json
x-auth-tokenBusiness: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJidXNpbmVzcyI6eyJpZCI6IjVlNGVjM2M3ZjUwODM3MjI0ODM5ZWRlNCJ9LCJpYXQiOjE1ODIyMjAyMzEsImV4cCI6MTU4NTgyMDIzMX0.htA0v6Id5K6PlkJ8u34cJKlEtB1WcOndlW-OBGEEF3E
###

// Availability
POST http://localhost:5000/api/availability
Content-Type: application/json
tokenBusiness: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJidXNpbmVzcyI6eyJpZCI6IjVlNWFlMTQzNzQ5NzI3MmI1OGQ5NTc5MiJ9LCJpYXQiOjE1ODMwMTQyMTEsImV4cCI6MTU4NjYxNDIxMX0.LGpegMzTwtYHcX3GpGitvSxQAbEIQ4Brsnd3VGYbFH0

{
      "day_of_week1": "Monday",
      "work1": "true",
      "start_time1": "13:00",
      "end_time1": "13:00",
      "start_lunch1": "13:00",
      "end_lunch1": "13:00",
      "day_of_week2": "Tuesday",
      "work2": "false",
      "start_time2": "13:00",
      "end_time2": "13:00",
      "start_lunch2": "13:00",
      "end_lunch2": "13:00",
      "day_of_week3": "Wensday",
      "work3": "false",
      "start_time3": "13:00",
      "end_time3": "13:00",
      "start_lunch3": "13:00",
      "end_lunch3": "13:00",
      "day_of_week4": "Thursday",
      "work4": "false",
      "start_time4": "13:00",
      "end_time4": "13:00",
      "start_lunch4": "13:00",
      "end_lunch4": "13:00",
      "day_of_week5": "Friday",
      "work5": "false",
      "start_time5": "13:00",
      "end_time5": "13:00",
      "start_lunch5": "13:00",
      "end_lunch5": "13:00",
      "day_of_week6": "Saturday",
      "work6": "false",
      "start_time6": "13:00",
      "end_time6": "13:00",
      "start_lunch6": "13:00",
      "end_lunch6": "13:00",
      "day_of_week7": "Sunday",
      "work7": "false",
      "start_time7": "13:00",
      "end_time7": "13:00",
      "start_lunch7": "13:00",
      "end_lunch7": "13:00"
}

###

// Grab availability data from business
GET http://localhost:5000/api/availability/work
Content-Type: application/json
x-auth-tokenBusiness: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJidXNpbmVzcyI6eyJpZCI6IjVlNTEwNTRlMDEwNDAyNTIzNDUyNmIwZCJ9LCJpYXQiOjE1ODIzNjgwNzksImV4cCI6MTU4NTk2ODA3OX0.zR1akeuGqG9-q793Rb9fkdNH2Mw9KiON49U9hpXQyFs

### 

// BussinessInfo test route
GET http://localhost:5000/api/businessinfo
Content-Type: application/json
### 

// BussinessInfo  route
POST http://localhost:5000/api/businessinfo
Content-Type: application/json
tokenBusiness: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJidXNpbmVzcyI6eyJpZCI6IjVlNWJlMGIyNGNmMDAwMGViYzVkYmVjMyJ9LCJpYXQiOjE1ODMwNzk2MDMsImV4cCI6MTU4NjY3OTYwM30.3ihJ36YjdN2bGyQMYEUAe66nXDXcZG-bmSwf8j6yxNk

{
"company":"Fuck",
"address": "6699 Broklen d street",
"city": "Sacramento",
"state": "California",
"zip": "95201",
"snapchat": "kutsSnap",
"instagram": "GetCutz",
"tiktok": "watchMeDance"
}
### 

// services test route
GET http://localhost:5000/api/services/test
Content-Type: application/json
### 

// services for hairstyles and cost saving to db
POST http://localhost:5000/api/services
Content-Type: application/json
tokenBusiness: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJidXNpbmVzcyI6eyJpZCI6IjVlNWJlMGIyNGNmMDAwMGViYzVkYmVjMyJ9LCJpYXQiOjE1ODMwNzk2MDMsImV4cCI6MTU4NjY3OTYwM30.3ihJ36YjdN2bGyQMYEUAe66nXDXcZG-bmSwf8j6yxNk

{
"lineUp":15,
"fade": 15,
"haircut": 20,
"edgeUp": 20,
"design": 25,
"buzzCut": 20,
"trim": 20,
"neckTrim": 20,
"extensionAddOn": 100,
"braids": 150,
"flatIron": 100,
"updo": 120,
"otherStyle": 120,
"bangTrim": 40,
"fullWeave": 50,
"quickWeave":30,
"sewInMaintenance":20,
"allOverColor": 100,
"bleachAndTone": 150,
"hairTint": 100,
"rootTouchUp": 150
}
###  

//  Bussiness info all
GET http://localhost:5000/api/businessinfo/all
Content-Type: application/json

### 

//  Bussiness info by db :id
GET http://localhost:5000/api/businessinfo/business/5e5bb9ed91a5a80a39cc8979
Content-Type: application/json
### 



// Delete a Bussiness 
DELETE  http://localhost:5000/api/businessinfo
Content-Type: application/json
x-auth-tokenBusiness: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJidXNpbmVzcyI6eyJpZCI6IjVlNTEwNTRlMDEwNDAyNTIzNDUyNmIwZCJ9LCJpYXQiOjE1ODIzNjgwNzksImV4cCI6MTU4NTk2ODA3OX0.zR1akeuGqG9-q793Rb9fkdNH2Mw9KiON49U9hpXQyFs
### 

//  Bussiness me
GET http://localhost:5000/api/businessinfo/me
Content-Type: application/json
tokenBusiness: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJidXNpbmVzcyI6eyJpZCI6IjVlNTZkOWU3OTIyOTA4MTI5YTdlODZjOSJ9LCJpYXQiOjE1ODI3NTAxODQsImV4cCI6MTU4NjM1MDE4NH0.nrtU15R9hes9t0O8OEpIH-Fa-yf0gCT5GvSNFue5p4g

### 
//todo

//  --------------Users -------------------- Users -------------------- Users


post http://localhost:5000/api/registerUser
Content-Type: application/json

{
    "name" : "sam",
    "email": "samsam3@email.com",
    "password": "123456"
}
### 
post http://localhost:5000/api/loginUser
Content-Type: application/json

{
    "email": "samsam2@email.com",
    "password": "123456"
}
### 

// search by zip code
post http://localhost:5000/api/businessinfo/zip
Content-Type: application/json

{
    "zip": "95209"
}
### 

// search by city
post http://localhost:5000/api/businessinfo/city
Content-Type: application/json
# tokenUser: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNWU1ZjRlOTFjYjU3MGI2Y2QwNzFhZjE2In0sImlhdCI6MTU4MzMwNDMzNywiZXhwIjoxNTg2OTA0MzM3fQ.wJqP_fxqT36BV-1FqNGLx-ZhvLVWnKKqoXc7N9TnZGU

{
    "city": "sacramento"
}
### 

post https://startup-barber.herokuapp.com/api/businessinfo/city

{
     "city": "sacramento"
}
### 