
// test Token
GET http://localhost:5000/api/login/token
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJidXNpbmVzcyI6eyJpZCI6IjVlNGVjM2M3ZjUwODM3MjI0ODM5ZWRlNCJ9LCJpYXQiOjE1ODIyMjAyMzEsImV4cCI6MTU4NTgyMDIzMX0.htA0v6Id5K6PlkJ8u34cJKlEtB1WcOndlW-OBGEEF3E
###

// test Token and see all user data 
GET http://localhost:5000/api/login/tokenUserID
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJidXNpbmVzcyI6eyJpZCI6IjVlNGVjM2M3ZjUwODM3MjI0ODM5ZWRlNCJ9LCJpYXQiOjE1ODIyMjAyMzEsImV4cCI6MTU4NTgyMDIzMX0.htA0v6Id5K6PlkJ8u34cJKlEtB1WcOndlW-OBGEEF3E
###

// test GET api
GET http://localhost:5000/api/login/test
Content-Type: application/json
###

// test POST api
POST http://localhost:5000/api/login/test
Content-Type: application/json

{
    "firstName" : "Otto",
    "lastName": "Kafka"
}
###

// client registration 
POST http://localhost:5000/api/login/client
Content-Type: application/json

{
    "name" : "Otto3",
    "email": "Kafka5@email.com",
    "password": "1234567890"
}
###

// Business registration 
POST http://localhost:5000/api/login/business
Content-Type: application/json

{
    "firstName" : "Otto",
    "lastName": "kafka",
    "email": "businessKakfa13@email.com",
    "password": "1234567890",
    "phoneNumber": "123456789"
}
###

// Business login 
POST http://localhost:5000/api/login/businessLogin
Content-Type: application/json

{
     "email": "businessKakfa8@email.com",
     "password": "1234567890"
}
###


// client login 
POST http://localhost:5000/api/login/clientLogin
Content-Type: application/json

{
    "email" : "Kafka5@email.com",
    "password": "1234567890"
}
###

// test GET api
GET http://localhost:5000/api/availability/test
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJidXNpbmVzcyI6eyJpZCI6IjVlNGVjM2M3ZjUwODM3MjI0ODM5ZWRlNCJ9LCJpYXQiOjE1ODIyMjAyMzEsImV4cCI6MTU4NTgyMDIzMX0.htA0v6Id5K6PlkJ8u34cJKlEtB1WcOndlW-OBGEEF3E
###

// Availability
POST http://localhost:5000/api/availability
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJidXNpbmVzcyI6eyJpZCI6IjVlNGVjM2M3ZjUwODM3MjI0ODM5ZWRlNCJ9LCJpYXQiOjE1ODIyMjAyMzEsImV4cCI6MTU4NTgyMDIzMX0.htA0v6Id5K6PlkJ8u34cJKlEtB1WcOndlW-OBGEEF3E

{
       "day_of_week1": "Monday",
      "work1": "true",
      "start_time1": "13:00",
      "end_time1": "13:00",
      "start_lunch1": "13:00",
      "end_lunch1": "13:00",
      "day_of_week2": "Tuesday",
      "work2": "false",
      "start_time2": "13:00",
      "end_time2": "13:00",
      "start_lunch2": "13:00",
      "end_lunch2": "13:00",
      "day_of_week3": "Wensday",
      "work3": "false",
      "start_time3": "13:00",
      "end_time3": "13:00",
      "start_lunch3": "13:00",
      "end_lunch3": "13:00",
      "day_of_week4": "Thursday",
      "work4": "false",
      "start_time4": "13:00",
      "end_time4": "13:00",
      "start_lunch4": "13:00",
      "end_lunch4": "13:00",
      "day_of_week5": "Friday",
      "work5": "false",
      "start_time5": "13:00",
      "end_time5": "13:00",
      "start_lunch5": "13:00",
      "end_lunch5": "13:00",
      "day_of_week6": "Saturday",
      "work6": "false",
      "start_time6": "13:00",
      "end_time6": "13:00",
      "start_lunch6": "13:00",
      "end_lunch6": "13:00",
      "day_of_week7": "Sunday",
      "work7": "false",
      "start_time7": "13:00",
      "end_time7": "13:00",
      "start_lunch7": "13:00",
      "end_lunch7": "13:00"
}
###

// Grab availability data from business
GET http://localhost:5000/api/availability/work
Content-Type: application/json
### 

// BussinessInfo test route
GET http://localhost:5000/api/businessinfo
Content-Type: application/json
### 

// BussinessInfo  route
POST http://localhost:5000/api/businessinfo
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJidXNpbmVzcyI6eyJpZCI6IjVlNGVjM2M3ZjUwODM3MjI0ODM5ZWRlNCJ9LCJpYXQiOjE1ODIyMjAyMzEsImV4cCI6MTU4NTgyMDIzMX0.htA0v6Id5K6PlkJ8u34cJKlEtB1WcOndlW-OBGEEF3E

{
"company":"get kut up g",
"address": "west killa street g",
"city": "sackramento Killas",
"state": "Cali baby",
"zip": "95201",
"snapchat": "kutsSnap",
"instagram": "GetCutz",
"tiktok": "watchMeDance"
}
### 

// services test route
GET http://localhost:5000/api/services/test
Content-Type: application/json
### 


// services to test hairstyle 
POST http://localhost:5000/api/businessinfo
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJidXNpbmVzcyI6eyJpZCI6IjVlNGVjM2M3ZjUwODM3MjI0ODM5ZWRlNCJ9LCJpYXQiOjE1ODIyMjAyMzEsImV4cCI6MTU4NTgyMDIzMX0.htA0v6Id5K6PlkJ8u34cJKlEtB1WcOndlW-OBGEEF3E

{
"company":"get kut up g",
"address": "west killa street g",
"city": "sackramento Killas",
"state": "Cali baby",
"zip": "95201",
"snapchat": "kutsSnap",
"instagram": "GetCutz",
"tiktok": "watchMeDance"
}
### 

// services for hairstyles and cost saving to db
POST http://localhost:5000/api/services
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJidXNpbmVzcyI6eyJpZCI6IjVlNGVjM2M3ZjUwODM3MjI0ODM5ZWRlNCJ9LCJpYXQiOjE1ODIyMjAyMzEsImV4cCI6MTU4NTgyMDIzMX0.htA0v6Id5K6PlkJ8u34cJKlEtB1WcOndlW-OBGEEF3E

{
"lineUp":15,
"fade": 15,
"haircut": 20,
"edgeUp": 20,
"design": 25,
"buzzCut": 20,
"trim": 20,
"neckTrim": 20,
"extensionAddOn": 100,
"braids": 150,
"flatIron": 100,
"updo": 120,
"otherStyle": 120,
"bangTrim": 40,
"fullWeave": 50,
"quickWeave":30,
"sewInMaintenance":20,
"allOverColor": 100,
"bleachAndTone": 150,
"hairTint": 100,
"rootTouchUp": 150
}
### 